### ISSUE TITLE
Tempo sync strategy

### ISSUE THREAD

**Issue by slipdef** [AllanHasegawa/Tempo#14]
From what I see here Tempo never stops synchronizing time source and updates activeTimeWrapper:
https://github.com/AllanHasegawa/Tempo/blob/master/tempo/src/main/java/io/tempo/internal/domain/useCases/PeriodicallySyncUC.kt#L16
https://github.com/AllanHasegawa/Tempo/blob/master/tempo/src/main/java/io/tempo/internal/TempoInstance.kt#L60

However you suggest to use a separate scheduler to fix a clock drift:
https://github.com/AllanHasegawa/Tempo#schedulers

What do I miss?

**Comment by AllanHasegawa** [comment]
Sorry about the late reply.

My use case for it is to keep the cache up-to-date on an offline-first app even when the app is not running since the WorkManager task will run even when the app is closed. That explanation for the scheduler that you pointed out was written when Tempo didn't have the automatic syncing while the app is running, so I can understand the confusion.

**Comment by slipdef** [comment]
Got it. I understand that simple call to Tempo.initialize results in the NTP network call every 5 mins. I would prefer not to have something firing network call that often without being explcit about that. Is there a way to stop that?

**Comment by AllanHasegawa** [comment]
Thanks for pointing it out. That's something I didn't consider with the refactor of the library, but it makes a lot of sense.

I'll check it later on. Should be a simple change to allow the app to chose the periodically sync behaviour.

**Comment by slipdef** [comment]
Ok, thanks for your answers. ATM I think the solution is to call Stop() manually when Tempo is initialized.
